# Generated by Django 5.2.4 on 2025-07-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_chat_id',
            field=models.CharField(blank=True, help_text='Enter your telegram chat id (NOT your username that starts with @)', max_length=50, null=True, verbose_name='telegram chat id'),
        ),
    ]
