# Generated by Django 5.2.4 on 2025-07-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_tg_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_chat_id',
            field=models.CharField(blank=True, help_text='id напиши', max_length=350, null=True, verbose_name='Телега'),
        ),
    ]
