# Generated by Django 5.2.4 on 2025-07-17 15:26

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit',
            field=models.CharField(help_text='Напиши что делаешь', max_length=255, verbose_name='Привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.PositiveSmallIntegerField(default=1, help_text='Укажите кол-во дней, за которые необходимо выполнить привычку (по умолчанию раз в день)', validators=[django.core.validators.MaxValueValidator(7)], verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='place_of_execution',
            field=models.CharField(blank=True, help_text='Напиши место', max_length=255, null=True, verbose_name='Место где нужно выполнять привычку'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='published',
            field=models.CharField(choices=[('Опубликован', 'Опубликован'), ('Не опубликован', 'Не опубликован')], default='Не опубликован', max_length=50, verbose_name='Статус опубликования привычки (по умолчанию Не опубликован)'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_habits', to='habits.habit', verbose_name='Связанная приятная привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, help_text='чем пользователь должен себя вознаградить после выполнения', null=True, verbose_name='Вознаграждение'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='sign_of_a_pleasant_habit',
            field=models.BooleanField(default=False, help_text='привычка, которую можно привязать к выполнению полезной привычки.', verbose_name='Признак полезной привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_execution',
            field=models.TimeField(blank=True, help_text='Время для выполнения привычки', null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.DurationField(default=datetime.timedelta(seconds=120), help_text='время, которое предположительно потратит пользователь на выполнение привычки (по умолчанию 120сек)', verbose_name='Время на действие'),
        ),
    ]
