# Generated by Django 5.2.4 on 2025-07-17 16:37

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_habit_alter_habit_periodicity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='Укажите кол-во дней, за которые необходимо выполнить привычку (по умолчанию раз в день)', null=True, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='published',
            field=models.CharField(blank=True, choices=[('Опубликован', 'Опубликован'), ('Не опубликован', 'Не опубликован')], default='Опубликован', max_length=50, null=True, verbose_name='Статус опубликования привычки (по умолчанию Не опубликован)'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='sign_of_a_pleasant_habit',
            field=models.BooleanField(blank=True, default=False, help_text='привычка, которую можно привязать к выполнению полезной привычки.', null=True, verbose_name='Признак полезной привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=120), help_text='время, которое предположительно потратит пользователь на выполнение привычки (по умолчанию 120сек)', null=True, verbose_name='Время на действие'),
        ),
    ]
