# Generated by Django 5.2.4 on 2025-07-18 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_periodicity_alter_habit_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='published',
            field=models.CharField(blank=True, choices=[('Опубликован', 'Опубликован'), ('Не опубликован', 'Не опубликован')], default='Не опубликован', max_length=50, null=True, verbose_name='Статус опубликования привычки (по умолчанию Не опубликован)'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, help_text='привычка, которую выполняем после полезной привычки (не может быть полезной и иметь вознаграждение)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_habits', to='habits.habit', verbose_name='Связанная приятная привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, help_text='чем пользователь должен себя вознаградить после выполнения (какой-то объект)', null=True, verbose_name='Вознаграждение'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='sign_of_a_pleasant_habit',
            field=models.BooleanField(blank=True, default=False, help_text='True - приятная привычка; False - полезная привычка (по умолчанию False)', null=True, verbose_name='Признак приятной привычки'),
        ),
    ]
