# Generated by Django 5.2.4 on 2025-07-18 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habit_published_alter_habit_related_habit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='send_indicator',
        ),
    ]
